### ISSUE TITLE
Backend Development

### ISSUE THREAD

**Issue by Petyo-Lukanov** [hashgraph/hedera-transaction-tool#301]
```[tasklist]
### Backend Flows
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/302
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/303
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/304
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/68
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/142
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/310
- [x] Notifications
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/375
```
