### ISSUE TITLE
Automation QA Work

### ISSUE THREAD

**Issue by Petyo-Lukanov** [hashgraph/hedera-transaction-tool#307]
All of the work around the automation QA process

```[tasklist]
### QA Tasks
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/308
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/318
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/319
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/337
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/364
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/365
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/390
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/391
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/392
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/393
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/394
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/395
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/396
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/397
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/398
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/548
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/596
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/620
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/644
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/683
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/695
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/704
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/917
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/936
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/984
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/1056
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/1218
```
