### ISSUE TITLE
Add support for HIP-869 Dynamic Address Book

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-transaction-tool#339]
### Problem

This HIP introduces NEW transactions that the council will be reviewing and signing on https://hips.hedera.com/hip/hip-869. 

New Transaction types:

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/985
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/986
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/987
```

This would be grouped under the category we have today called: node. This should probably be renamed to Node Management and the sub categories would be create a node, delete a node, update a node. 

### Solution

Add support for the new transaction types in the UI
