### ISSUE TITLE
Login & Application Setup

### ISSUE THREAD

**Issue by Petyo-Lukanov** [hashgraph/hedera-transaction-tool#56]
### Problem

The team have worked on the PoC of the Login and Application Setup flows and we have it completed for the purposes of a PoC. We still need to, however, update the frontend based on the final designs once they are ready. This could take several iterations as there might be ongoing updates required based on stakeholders' feedback. 

### Solution

Within this Epic we will outline the main screens that will certainly be worked on.

```[tasklist]
### Login & Application Setup Frontend Development
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/92
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/93
```

```[tasklist]
### Functionalities
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/69
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/86
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/87
```
