### ISSUE TITLE
Email notifications for organizational user

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-transaction-tool#560]
### Problem

When a transaction is created for an organization, significant coordination is required between the creator, approver, and signer. By having the application manage this coordination, the process becomes easier to handle, enhancing efficiency and providing a more seamless user experience.

### Solution

- [x] https://github.com/hashgraph/hedera-transaction-tool/issues/557
- [x] https://github.com/hashgraph/hedera-transaction-tool/issues/558
- [x] https://github.com/hashgraph/hedera-transaction-tool/issues/559
- [x] #561
- [x] https://github.com/hashgraph/hedera-transaction-tool/issues/562

**Comment by jbair06** [comment]
When approvers is implemented, depending on the implementation, this may need to be altered slightly. For example, perhaps the approvers receive the first notification, then once approved the signers will then receive the notification.

**Comment by jbair06** [comment]
Signers may want to receive an email when a transaction they've signed has successfully executed. They will also likely want to be able to turn off certain email notification types.
