### ISSUE TITLE
Fix issues from the internal audit report

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-transaction-tool#567]
### Problem

Fix issues identified in the internal audit report. 

### Solution

Fix issues identified in the internal audit report. 

- [x] https://github.com/hashgraph/hedera-transaction-tool/issues/722
- [x] https://github.com/hashgraph/hedera-transaction-tool/issues/721
- [x] https://github.com/hashgraph/hedera-transaction-tool/issues/720
- [x] https://github.com/hashgraph/hedera-transaction-tool/issues/719
- [x] https://github.com/hashgraph/hedera-transaction-tool/issues/718
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/717
- [x] https://github.com/hashgraph/hedera-transaction-tool/issues/716
- [x] https://github.com/hashgraph/hedera-transaction-tool/issues/715
