### ISSUE TITLE
Accounts & Account Management

### ISSUE THREAD

**Issue by Petyo-Lukanov** [hashgraph/hedera-transaction-tool#58]
### Problem

Users should be able to operate with Accounts in the Application. The operations that are required are the following: 
- Link/Add Account - Simply "import" any Hedera Account in the application by providing the Account ID 
- Unlink/Remove Account - Remove an account from your list of accounts in the Application - This simply removes the account and is not a Delete operation
- Create Account - Create Account operation 
- Delete Account - Delete Account operation

### Solution

Implement the Frontend look and feel based on the designs to support the above mentioned operations.

```[tasklist]
### Account Operations Functionalities Development \[Personal User]
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/80
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/81
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/102
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/82
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/83
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/84
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/174
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/79
```

```[tasklist]
### Tasks
```
