### ISSUE TITLE
Email Notifications - PoC

### ISSUE THREAD

**Issue by Petyo-Lukanov** [hashgraph/hedera-transaction-tool#627]
For the purpose of introducing a more sophisticated Notification system across the Transaction Tool, we will initially start with two main email notifications, which users will receive when:
- Transaction Signature is required from the user -> This will be mostly useful for Transaction Signers 
- When all Signatures for a certain transaction has been received -> This info should be mostly useful for TX creators, but might also be welcomed by the TX signers as well

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/558
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/628
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/632
```
