### ISSUE TITLE
File Management

### ISSUE THREAD

**Issue by Petyo-Lukanov** [hashgraph/hedera-transaction-tool#65]
### Problem

This Epic includes all of the work items related to the implementation of File Management related operations. 

### Solution

Go through all issues in the Epic and resolve/implement the solutions. 

```[tasklist]
### File Management Functionalities
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/88
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/89
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/90
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/91
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/135
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/173
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/190
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/191
```

```[tasklist]
### File Management Frontend Development
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/214
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/215
```
