### ISSUE TITLE
Set-up application backend 

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-transaction-tool#68]
### Problem

When adding an organization to the application we need a test backend environment to test this use case.

This includes:
- a Postgres database set up
- Helm chart 
- Kubernetes cluster 

### Solution

Set-up the test environment to test the organizational use case. This will only be used for testing purposes. Eventually it would need to be deployed to an environment so that we can test multiple users connecting to the backend. 

```[tasklist]
### Tasks
- [x] Complete backend design document
- [x] Set-up local instance of the backend server/database
- [x] Research local kubernetes/database testing
- [x] Set-up test environment for manual testing (devOps)
```
