### ISSUE TITLE
Define local storage for the application for personal use

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-transaction-tool#69]
### Problem

When a user sets up the application, the data for the application needs to be stored locally on the users device for a personal user.

### Solution

Define where the data will be stored for the personal user when using the application.

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/94
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/95
- [x] Integrate local storage solution with front end
```
