### ISSUE TITLE
Transaction Management

### ISSUE THREAD

**Issue by Petyo-Lukanov** [hashgraph/hedera-transaction-tool#97]
### Problem

This is an Epic that consists of all issues required for the completion of the Transaction Management functionality of the App.

### Solution

Complete all issues from the Epic. 

```[tasklist]
### Transactions Functionalities
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/98
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/99
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/104
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/103
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/253
```

```[tasklist]
### Transaction Management Frontend Development
- [ ] https://github.com/hashgraph/hedera-transaction-tool/issues/204
```
